# Generated by Django 3.2.9 on 2022-02-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220129_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('computer', 'Computer'), ('business', 'Business')], default='computer', max_length=50),
        ),
    ]
