# Generated by Django 3.2.9 on 2022-02-23 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpost_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='day',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='month',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='today',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
