# Generated by Django 3.2.9 on 2022-02-24 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220223_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='today',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
