# Generated by Django 3.2.9 on 2022-02-24 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('technology', 'Technology'), ('business', 'Business')], default='technology', max_length=50),
        ),
    ]
